# Print configuration summary
message(STATUS "")
message(STATUS "Miko Configuration Summary:")
message(STATUS "================================")
message(STATUS "  Version: ${PROJECT_VERSION}")
message(STATUS "  Platform: ${MIKO_PLATFORM}")
message(STATUS "  Graphics API: ${MIKO_GRAPHICS_API}")
message(STATUS "  SDL2 Version: ${SDL2_VERSION}")
message(STATUS "  Build Examples: ${MIKO_BUILD_EXAMPLES}")
message(STATUS "  Build Tests: ${MIKO_BUILD_TESTS}")
message(STATUS "  Screen Capture: ${MIKO_ENABLE_SCREEN_CAPTURE}")
message(STATUS "  HTTP Client: ${MIKO_ENABLE_HTTP_CLIENT}")
message(STATUS "  Inspector: ${MIKO_ENABLE_INSPECTOR}")
message(STATUS "  Leak Detection: ${MIKO_ENABLE_LEAK_DETECTION}")
message(STATUS "  Runtime Shaders: ${MIKO_RUNTIME_SHADERS}")
message(STATUS "  Auto Build Deps: ${MIKO_AUTO_BUILD_DEPS}")
message(STATUS "")

# Development hints
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "Development Tips:")
    message(STATUS "  - Use 'make -j$(nproc)' for parallel builds")
    message(STATUS "  - Run examples from: ${CMAKE_BINARY_DIR}/examples/")
    if(MIKO_ENABLE_LEAK_DETECTION AND UNIX)
        message(STATUS "  - Memory leaks will be detected with AddressSanitizer")
    endif()
    message(STATUS "")
endif()